### ISSUE TITLE
Edit tag

### ISSUE THREAD

**Issue by martinbouhier** [eduNEXT/eox-tagging#82]
Hi, is there any way to edit a created tag? Or I need to destroy and then created again with different value?
Thanks

**Comment by mariajgrimaldi** [comment]
Hello! Thanks for reaching out. 

While designing the tagging functionality, we decided not to allow edits to the tags records to maintain a trail record over each tag. One thing we recommend doing is:

1. Delete the existing tag (deleting a tag means to deactivate, kind of a soft deletion)
2. Add a new one

I hope this helps!
