### ISSUE TITLE
Error getting user object

### ISSUE THREAD

**Issue by martinbouhier** [eduNEXT/eox-tagging#89]
I can't create an user tag. Is there any field I missed?

Error
```
{
    "Target": "Error getting user object."
}
```

common.py:

```
        {
            "tag_type": "membership",
            "validate_owner_object": "Site"
            "validate_target_object": "user",
            "validate_access": {"equals": "PUBLIC"},
            "validate_tag_value": {
                "exist":True
            },
        }

```

request
```
curl --location --request POST 'http://localhost:18000/eox-tagging/api/v1/tags/' \
--header 'Authorization: Bearer Token' \
--header 'Content-Type: application/json' \
--header 'Cookie: openedx-language-preference=es-419' \
--data-raw '{
    "tag_type": "membership",
    "tag_value": "basic",
    "target_type": "user",
    "target_id": "edx"
}'
```

**Comment by angetresca-mercadolibre** [comment]
I'm having the same issue, with other config:

Definitions:
```
[{"tag_type": "user-team", "target_object": "user"}, 
{"tag_type": "course-team", "target_object": "opaquekeyproxymodel"}]
```

Request:
```

curl --location --request POST 'http://local.overhang.io/eox-tagging/api/v1/tags/' \
--header 'Authorization: Bearer token' \
--data-raw '{
    "tag_type": "user-team",
    "tag_value": "code-eco",
    "target_type": "user",
    "target_id": "atresca",
    "access": "PRIVATE"
}'
```

Response:
```

{
    "Target": "Error getting user object."
}
```

**Comment by mariajgrimaldi** [comment]
Hi! Sorry for the delay. Did you create that user on your site? That error usually happens when you try to tag a user that wasn't created on the site making the call :thinking: 

You can check if the user was created on the site using:
```
select * from student_userattribute as s inner join auth_user as a where s.user_id=a.id and a.username="replace me";
```

**Comment by mariajgrimaldi** [comment]
I believe that's not the same as registering using the registration form, can you test with that? :thinking:

**Comment by angetresca-mercadolibre** [comment]
@mariajgrimaldi You're right, with an user registered by the registration form this worked ok. What's the difference between this two users?

**Comment by mariajgrimaldi** [comment]
When you create a user using the registration form, some other records are created: like ``UserAttributes`` you can see the records here `admin/student/userattribute/`. Now, eox-tagging when tagging first needs to [get the object](https://github.com/eduNEXT/eox-tagging/blob/master/eox_tagging/api/v1/serializers.py#L63), in this case, the `user`:

- To do this uses a method from eox-core: [get_edxapp_user](https://github.com/eduNEXT/eox-core/blob/master/eox_core/edxapp_wrapper/backends/users_l_v1.py#L193)
- The method checks for `FetchUserSiteSources` configured by [this](https://github.com/eduNEXT/eox-core/blob/master/eox_core/settings/common.py#L45) setting that by default is:
```
settings.EOX_CORE_USER_ORIGIN_SITE_SOURCES = [
            'fetch_from_created_on_site_prop',
            'fetch_from_user_signup_source',
        ]
```
Meaning: when getting a user, check that the user passes one of those two checks -implemented [here](https://github.com/eduNEXT/eox-core/blob/c2d8d37707fb0b7b83b9efa493abf3e1cc068edc/eox_core/edxapp_wrapper/backends/users_l_v1.py#L317-L331)-. In your case: `fetch_from_created_on_site_prop`. If you check the user you just registered I bet it has that record.

If you want to disable this behavior -used in multitenant installations so we can have a sense of _user_ belonging- then change  [this](https://github.com/eduNEXT/eox-core/blob/master/eox_core/settings/common.py#L44) setting to `False`

Hope this helps!

**Comment by Thargelion** [comment]
I get this working using: fetch_from_unfiltered_table as EOX_CORE_USER_ORIGIN_SITE_SOURCES.

In our case we don't have neither multitenancy nor registration.

**Comment by mariajgrimaldi** [comment]
That's also a way of doing it :) @Thargelion

**Comment by dcoa** [comment]
Hi, this issue was resolved with the previous explanation,  I'm going to close this. 😊
