### ISSUE TITLE
Error tagging site object

### ISSUE THREAD

**Issue by lugovlac** [eduNEXT/eox-tagging#90]
I'm having an error when trying to tag a "Site" object:

{
    "Target": "Error getting site object."
}

Definition:

{
    "tag_type": "example_tag_4",
    "target_object": "Site"
}

API call Body:

{
  "tag_value": "hola_un_valor",
  "tag_type": "example_tag_4",
  "target_id": "example.com",
  "target_type": "Site"
}

No matter what I write in target_id, I tried all sites loaded in /admin , also the numerical ids (1, 2, etc), nothing seems to work. I'm using my local environment.
Thanks.

**Comment by lugovlac** [comment]
The "GeneratedCertificate" target_object does not work either. Error:

{
    "Target": "Error getting GeneratedCertificate object."
}

Definition:

{
    "tag_type": "example_tag_5",
    "target_object": "GeneratedCertificate"
}

Body:

{
  "tag_value": "un_valor",
  "tag_type": "example_tag_5",
  "target_id": "edx:course-v1:LaOrganizacion1+fdsafsdaf+v1",
  "target_type": "GeneratedCertificate"
}

Tried with all courses completed by the user "edx" as target_id .

**Comment by dcoa** [comment]
Hi @lugovlac sorry for the response time, thanks for your report we are checking it.

For certificates, it's possible an eox-core backend is missed, could you verify you have this in `eox_core/settings/common.py`
```yml
EOX_CORE_CERTIFICATES_BACKEND: eox_core.edxapp_wrapper.backends.certificates_m_v1
```
Let me know if this works for you.
